version: '3'

services:
  narutoDB:
    image: mysql:8
    container_name: narutoDB
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d/ # Monta tus scripts aquí
    ports:
      - "3307:3306"

  naruto_app:
    depends_on:
      - narutoDB
    build:
      context: .
      dockerfile: Dockerfile
    image: naruto_sets:0.0.1
    ports:
      - "8888:8888"

volumes:
  mysql_data:
