INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('amegakure amulet','amegakure accessories','chakra','chakra',54000,NULL),
	 ('amegakure bangle','amegakure accessories','agility','agility',54000,NULL),
	 ('amegakure bracelet','amegakure accessories','agility','agility',54000,NULL),
	 ('amegakure gloves','amegakure accessories','power','power',540000,NULL),
	 ('amegakure headband','amegakure accessories','force','force',54000,NULL),
	 ('amegakure necklace','amegakure accessories','force','force',54000,NULL),
	 ('amegakure pendant','amegakure accessories','chakra','chakra',54000,NULL),
	 ('amegakure ring','amegakure accessories','power','power',540000,NULL),
	 ('amenonuhoko amulet','amenonuhoko accessories','chakra','chakra',54000,NULL),
	 ('amenonuhoko bangle','amenonuhoko accessories','agility','agility',54000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('amenonuhoko bracelet','amenonuhoko accessories','agility','agility',54000,NULL),
	 ('amenonuhoko gloves','amenonuhoko accessories','power','power',540000,NULL),
	 ('amenonuhoko headband','amenonuhoko accessories','force','force',54000,NULL),
	 ('amenonuhoko necklace','amenonuhoko accessories','force','force',54000,NULL),
	 ('amenonuhoko pendant','amenonuhoko accessories','chakra','chakra',54000,NULL),
	 ('amenonuhoko ring','amenonuhoko accessories','power','power',540000,NULL),
	 ('arcane amulet','arcane accessories','chakra','chakra',61000,NULL),
	 ('arcane bangle','arcane accessories','agility','agility',61000,NULL),
	 ('arcane bracelet','arcane accessories','agility','agility',61000,NULL),
	 ('arcane gloves','arcane accessories','power','power',610000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('arcane headband','arcane accessories','force','force',61000,NULL),
	 ('arcane necklace','arcane accessories','force','force',61000,NULL),
	 ('arcane pendant','arcane accessories','chakra','chakra',61000,NULL),
	 ('arcane ring','arcane accessories','power','power',61000,NULL),
	 ('ashura amulet','ashura accessories','chakra','chakra',45000,NULL),
	 ('ashura bangle','ashura accessories','agility','agility',47000,NULL),
	 ('ashura bracelet','ashura accessories','agility','agility',47000,NULL),
	 ('ashura gloves','ashura accessories','power','power',460000,NULL),
	 ('ashura headband','ashura accessories','force','force',45000,NULL),
	 ('ashura necklace','ashura accessories','force','force',45000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('ashura pendant','ashura accessories','chakra','chakra',45000,NULL),
	 ('ashura ring','ashura accessories','power','power',460000,NULL),
	 ('butterfly amulet','butterfly accessories','chakra','chakra',605000,NULL),
	 ('butterfly bangle','butterfly accessories','agility','agility',60500,NULL),
	 ('butterfly bracelet','butterfly accessories','agility','agility',60500,NULL),
	 ('butterfly gloves','butterfly accessories','power','power',60500,NULL),
	 ('butterfly headband','butterfly accessories','force','force',60500,NULL),
	 ('butterfly necklace','butterfly accessories','force','force',60500,NULL),
	 ('butterfly pendant','butterfly accessories','chakra','chakra',60500,NULL),
	 ('butterfly ring','butterfly accessories','power','power',60500,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('corruptor amulet','corruptor accessories','chakra','chakra',38000,NULL),
	 ('corruptor bangle','corruptor accessories','agility','agility',40000,NULL),
	 ('corruptor bracelet','corruptor accessories','agility','agility',40000,NULL),
	 ('corruptor gloves','corruptor accessories','power','power',400000,NULL),
	 ('corruptor headband','corruptor accessories','force','force',38000,NULL),
	 ('corruptor necklace','corruptor accessories','force','force',38000,NULL),
	 ('corruptor pendant','corruptor accessories','chakra','chakra',38000,NULL),
	 ('corruptor ring','corruptor accessories','power','power',400000,NULL),
	 ('cursed amulet','cursed accessories','chakra','chakra',51000,NULL),
	 ('cursed bangle','cursed accessories','agility','agility',53000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('cursed bracelet','cursed accessories','agility','agility',53000,NULL),
	 ('cursed gloves','cursed accessories','power','power',520000,NULL),
	 ('cursed headband','cursed accessories','force','force',51000,NULL),
	 ('cursed necklace','cursed accessories','force','force',51000,NULL),
	 ('cursed pendant','cursed accessories','chakra','chakra',51000,NULL),
	 ('cursed ring','cursed accessories','power','power',520000,NULL),
	 ('deathbone amulet','deathbone accessories','chakra','chakra',28000,NULL),
	 ('deathbone bangle','deathbone accessories','agility','agility',32000,NULL),
	 ('deathbone bracelet','deathbone accessories','agility','agility',32000,NULL),
	 ('deathbone gloves','deathbone accessories','power','power',320000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('deathbone headband','deathbone accessories','force','force',28000,NULL),
	 ('deathbone necklace','deathbone accessories','force','force',28000,NULL),
	 ('deathbone pendant','deathbone accessories','chakra','chakra',28000,NULL),
	 ('deathbone ring','deathbone accessories','power','power',320000,NULL),
	 ('devout amulet','devout accessories','chakra','chakra',34000,NULL),
	 ('devout bangle','devout accessories','agility','agility',38000,NULL),
	 ('devout bracelet','devout accessories','agility','agility',38000,NULL),
	 ('devout gloves','devout accessories','power','power',380000,NULL),
	 ('devout headband','devout accessories','force','force',34000,NULL),
	 ('devout necklace','devout accessories','force','force',34000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('devout pendant','devout accessories','chakra','chakra',34000,NULL),
	 ('devout ring','devout accessories','power','power',380000,NULL),
	 ('guard amulet','guard accessories','chakra','chakra',570000,NULL),
	 ('guard bangle','guard accessories','agility','agility',57000,NULL),
	 ('guard bracelet','guard accessories','agility','agility',57000,NULL),
	 ('guard gloves','guard accessories','power','power',57000,NULL),
	 ('guard headband','guard accessories','force','force',57000,NULL),
	 ('guard necklace','guard accessories','force','force',57000,NULL),
	 ('guard pendant','guard accessories','chakra','chakra',57000,NULL),
	 ('guard ring','guard accessories','power','power',57000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('guren amulet','guren accessories','chakra','chakra',57500,NULL),
	 ('guren bangle','guren accessories','agility','agility',57500,NULL),
	 ('guren bracelet','guren accessories','agility','agility',57500,NULL),
	 ('guren gloves','guren accessories','power','power',575000,NULL),
	 ('guren headband','guren accessories','force','force',57500,NULL),
	 ('guren necklace','guren accessories','force','force',57500,NULL),
	 ('guren pendant','guren accessories','chakra','chakra',57500,NULL),
	 ('guren ring','guren accessories','power','power',575000,NULL),
	 ('heroism amulet','heroism accessories','chakra','chakra',40000,NULL),
	 ('heroism bangle','heroism accessories','agility','agility',42000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('heroism bracelet','heroism accessories','agility','agility',42000,NULL),
	 ('heroism gloves','heroism accessories','power','power',420000,NULL),
	 ('heroism headband','heroism accessories','force','force',40000,NULL),
	 ('heroism necklace','heroism accessories','force','force',40000,NULL),
	 ('heroism pendant','heroism accessories','chakra','chakra',40000,NULL),
	 ('heroism ring','heroism accessories','power','power',420000,NULL),
	 ('hyuuga amulet','hyuuga accessories','chakra','chakra',48000,NULL),
	 ('hyuuga bangle','hyuuga accessories','agility','agility',50000,NULL),
	 ('hyuuga bracelet','hyuuga accessories','agility','agility',50000,NULL),
	 ('hyuuga gloves','hyuuga accessories','power','power',490000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('hyuuga headband','hyuuga accessories','force','force',48000,NULL),
	 ('hyuuga necklace','hyuuga accessories','force','force',48000,NULL),
	 ('hyuuga pendant','hyuuga accessories','chakra','chakra',48000,NULL),
	 ('hyuuga ring','hyuuga accessories','power','power',490000,NULL),
	 ('indora amulet','indora accessories','chakra','chakra',43000,NULL),
	 ('indora bangle','indora accessories','agility','agility',45000,NULL),
	 ('indora bracelet','indora accessories','agility','agility',45000,NULL),
	 ('indora gloves','indora accessories','power','power',450000,NULL),
	 ('indora headband','indora accessories','force','force',43000,NULL),
	 ('indora necklace','indora accessories','force','force',43000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('indora pendant','indora accessories','chakra','chakra',43000,NULL),
	 ('indora ring','indora accessories','power','power',450000,NULL),
	 ('infernity amulet','infernity accessories','chakra','chakra',60000,NULL),
	 ('infernity bangle','infernity accessories','agility','agility',60000,NULL),
	 ('infernity bracelet','infernity accessories','agility','agility',60000,NULL),
	 ('infernity gloves','infernity accessories','power','power',600000,NULL),
	 ('infernity headband','infernity accessories','force','force',60000,NULL),
	 ('infernity necklace','infernity accessories','force','force',60000,NULL),
	 ('infernity pendant','infernity accessories','chakra','chakra',60000,NULL),
	 ('infernity ring','infernity accessories','power','power',600000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('kaguya amulet','kaguya accessories','chakra','chakra',44000,NULL),
	 ('kaguya bangle','kaguya accessories','agility','agility',46000,NULL),
	 ('kaguya bracelet','kaguya accessories','agility','agility',46000,NULL),
	 ('kaguya gloves','kaguya accessories','power','power',460000,NULL),
	 ('kaguya headband','kaguya accessories','force','force',44000,NULL),
	 ('kaguya necklace','kaguya accessories','force','force',44000,NULL),
	 ('kaguya pendant','kaguya accessories','chakra','chakra',44000,NULL),
	 ('kaguya ring','kaguya accessories','power','power',460000,NULL),
	 ('kirikakure amulet','kirikakure accessories','chakra','chakra',52000,NULL),
	 ('kirikakure bangle','kirikakure accessories','agility','agility',54000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('kirikakure bracelet','kirikakure accessories','agility','agility',54000,NULL),
	 ('kirikakure gloves','kirikakure accessories','power','power',530000,NULL),
	 ('kirikakure headband','kirikakure accessories','force','force',52000,NULL),
	 ('kirikakure necklace','kirikakure accessories','force','force',52000,NULL),
	 ('kirikakure pendant','kirikakure accessories','chakra','chakra',52000,NULL),
	 ('kirikakure ring','kirikakure accessories','power','power',530000,NULL),
	 ('kumogakure amulet','kumogakure accessories','chakra','chakra',52500,NULL),
	 ('kumogakure bangle','kumogakure accessories','agility','agility',54000,NULL),
	 ('kumogakure bracelet','kumogakure accessories','agility','agility',54000,NULL),
	 ('kumogakure gloves','kumogakure accessories','power','power',530000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('kumogakure headband','kumogakure accessories','force','force',52500,NULL),
	 ('kumogakure necklace','kumogakure accessories','force','force',52500,NULL),
	 ('kumogakure pendant','kumogakure accessories','chakra','chakra',52500,NULL),
	 ('kumogakure ring','kumogakure accessories','power','power',530000,NULL),
	 ('kumogakure(gen) amulet','kumogakure(gen) accessories','chakra','chakra',52500,NULL),
	 ('kumogakure(gen) bangle','kumogakure(gen) accessories','agility','agility',54000,NULL),
	 ('kumogakure(gen) bracelet','kumogakure(gen) accessories','agility','agility',54000,NULL),
	 ('kumogakure(gen) gloves','kumogakure(gen) accessories','power','power',530000,NULL),
	 ('kumogakure(gen) headband','kumogakure(gen) accessories','force','force',52500,NULL),
	 ('kumogakure(gen) necklace','kumogakure(gen) accessories','force','force',52500,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('kumogakure(gen) pendant','kumogakure(gen) accessories','chakra','chakra',52500,NULL),
	 ('kumogakure(gen) ring','kumogakure(gen) accessories','power','power',530000,NULL),
	 ('longen amulet','longen accessories','chakra','chakra',53000,NULL),
	 ('longen bangle','longen accessories','agility','agility',54500,NULL),
	 ('longen bracelet','longen accessories','agility','agility',54500,NULL),
	 ('longen gloves','longen accessories','power','power',535000,NULL),
	 ('longen headband','longen accessories','force','force',53000,NULL),
	 ('longen necklace','longen accessories','force','force',53000,NULL),
	 ('longen pendant','longen accessories','chakra','chakra',53000,NULL),
	 ('longen ring','longen accessories','power','power',535000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('moonlit amulet','moonlit accessories','chakra','chakra',59500,NULL),
	 ('moonlit bangle','moonlit accessories','agility','agility',59500,NULL),
	 ('moonlit bracelet','moonlit accessories','agility','agility',59500,NULL),
	 ('moonlit gloves','moonlit accessories','power','power',595000,NULL),
	 ('moonlit headband','moonlit accessories','force','force',59500,NULL),
	 ('moonlit necklace','moonlit accessories','force','force',59500,NULL),
	 ('moonlit pendant','moonlit accessories','chakra','chakra',59500,NULL),
	 ('moonlit ring','moonlit accessories','power','power',595000,NULL),
	 ('oblivion  bracelet','oblivion accessories','agility','agility',40000,NULL),
	 ('oblivion amulet','oblivion accessories','chakra','chakra',36000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('oblivion bangle','oblivion accessories','agility','agility',40000,NULL),
	 ('oblivion gloves','oblivion accessories','power','power',400000,NULL),
	 ('oblivion headband','oblivion accessories','force','force',36000,NULL),
	 ('oblivion necklace','oblivion accessories','force','force',36000,NULL),
	 ('oblivion pendant','oblivion accessories','chakra','chakra',36000,NULL),
	 ('oblivion ring','oblivion accessories','power','power',400000,NULL),
	 ('otsutsuki amulet','otsutsuki accessories','chakra','chakra',42000,NULL),
	 ('otsutsuki bangle','otsutsuki accessories','agility','agility',42000,NULL),
	 ('otsutsuki bracelet','otsutsuki accessories','agility','agility',42000,NULL),
	 ('otsutsuki gloves','otsutsuki accessories','power','power',420000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('otsutsuki headband','otsutsuki accessories','force','force',42000,NULL),
	 ('otsutsuki necklace','otsutsuki accessories','force','force',42000,NULL),
	 ('otsutsuki pendant','otsutsuki accessories','chakra','chakra',42000,NULL),
	 ('otsutsuki ring','otsutsuki accessories','power','power',420000,NULL),
	 ('pain amulet','pain accessories','chakra','chakra',56500,NULL),
	 ('pain bangle','pain accessories','agility','agility',56500,NULL),
	 ('pain bracelet','pain accessories','agility','agility',56500,NULL),
	 ('pain gloves','pain accessories','power','power',565000,NULL),
	 ('pain headband','pain accessories','force','force',56500,NULL),
	 ('pain necklace','pain accessories','force','force',56500,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('pain pendant','pain accessories','chakra','chakra',56500,NULL),
	 ('pain ring','pain accessories','power','power',565000,NULL),
	 ('reanimated amulet','reanimated accessories','chakra','chakra',54000,NULL),
	 ('reanimated bangle','reanimated accessories','agility','agility',54000,NULL),
	 ('reanimated bracelet','reanimated accessories','agility','agility',54000,NULL),
	 ('reanimated gloves','reanimated accessories','power','power',540000,NULL),
	 ('reanimated headband','reanimated accessories','force','force',54000,NULL),
	 ('reanimated necklace','reanimated accessories','force','force',54000,NULL),
	 ('reanimated pendant','reanimated accessories','chakra','chakra',54000,NULL),
	 ('reanimated ring','reanimated accessories','power','power',540000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('saint amulet','saint accessories','chakra','chakra',40000,NULL),
	 ('saint bangle','saint accessories','agility','agility',40000,NULL),
	 ('saint bracelet','saint accessories','agility','agility',40000,NULL),
	 ('saint gloves','saint accessories','power','power',400000,NULL),
	 ('saint headband','saint accessories','force','force',40000,NULL),
	 ('saint necklace','saint accessories','force','force',40000,NULL),
	 ('saint pendant','saint accessories','chakra','chakra',40000,NULL),
	 ('saint ring','saint accessories','power','power',400000,NULL),
	 ('sakura amulet','sakura accessories','chakra','chakra',53500,NULL),
	 ('sakura bangle','sakura accessories','agility','agility',55000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('sakura bracelet','sakura accessories','agility','agility',55000,NULL),
	 ('sakura gloves','sakura accessories','power','power',540000,NULL),
	 ('sakura headband','sakura accessories','force','force',53500,NULL),
	 ('sakura necklace','sakura accessories','force','force',53500,NULL),
	 ('sakura pendant','sakura accessories','chakra','chakra',53500,NULL),
	 ('sakura ring','sakura accessories','power','power',540000,NULL),
	 ('sarutobi defend amulet','sarutobi defend accessories','chakra','chakra',50000,NULL),
	 ('sarutobi defend bangle','sarutobi defend accessories','agility','agility',52000,NULL),
	 ('sarutobi defend bracelet','sarutobi defend accessories','agility','agility',52000,NULL),
	 ('sarutobi defend gloves','sarutobi defend accessories','power','power',510000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('sarutobi defend headband','sarutobi defend accessories','force','force',50000,NULL),
	 ('sarutobi defend necklace','sarutobi defend accessories','force','force',50000,NULL),
	 ('sarutobi defend pendant','sarutobi defend accessories','chakra','chakra',50000,NULL),
	 ('sarutobi defend ring','sarutobi defend accessories','power','power',510000,NULL),
	 ('sarutobi raid amulet','sarutobi raid accessories','chakra','chakra',50000,NULL),
	 ('sarutobi raid bangle','sarutobi raid accessories','agility','agility',52000,NULL),
	 ('sarutobi raid bracelet','sarutobi raid accessories','agility','agility',52000,NULL),
	 ('sarutobi raid gloves','sarutobi raid accessories','power','power',510000,NULL),
	 ('sarutobi raid headband','sarutobi raid accessories','force','force',50000,NULL),
	 ('sarutobi raid necklace','sarutobi raid accessories','force','force',50000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('sarutobi raid pendant','sarutobi raid accessories','chakra','chakra',50000,NULL),
	 ('sarutobi raid ring','sarutobi raid accessories','power','power',510000,NULL),
	 ('senju amulet','senju accessories','chakra','chakra',46000,NULL),
	 ('senju bangle','senju accessories','agility','agility',48000,NULL),
	 ('senju bracelet','senju accessories','agility','agility',48000,NULL),
	 ('senju gloves','senju accessories','power','power',470000,NULL),
	 ('senju headband','senju accessories','force','force',46000,NULL),
	 ('senju necklace','senju accessories','force','force',46000,NULL),
	 ('senju pendant','senju accessories','chakra','chakra',46000,NULL),
	 ('senju ring','senju accessories','power','power',470000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('skyshatter amulet','skyshatter accessories','chakra','chakra',32000,NULL),
	 ('skyshatter bangle','skyshatter accessories','agility','agility',36000,NULL),
	 ('skyshatter bracelet','skyshatter accessories','agility','agility',36000,NULL),
	 ('skyshatter gloves','skyshatter accessories','power','power',360000,NULL),
	 ('skyshatter headband','skyshatter accessories','force','force',32000,NULL),
	 ('skyshatter necklace','skyshatter accessories','force','force',32000,NULL),
	 ('skyshatter pendant','skyshatter accessories','chakra','chakra',32000,NULL),
	 ('skyshatter ring','skyshatter accessories','power','power',360000,NULL),
	 ('sunagakure amulet','sunagakure accessories','chakra','chakra',55000,NULL),
	 ('sunagakure bangle','sunagakure accessories','agility','agility',55000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('sunagakure bracelet','sunagakure accessories','agility','agility',55000,NULL),
	 ('sunagakure gloves','sunagakure accessories','power','power',550000,NULL),
	 ('sunagakure headband','sunagakure accessories','force','force',55000,NULL),
	 ('sunagakure necklace','sunagakure accessories','force','force',55000,NULL),
	 ('sunagakure pendant','sunagakure accessories','chakra','chakra',55000,NULL),
	 ('sunagakure ring','sunagakure accessories','power','power',550000,NULL),
	 ('sunfire amulet','sunfire accessories','chakra','chakra',58000,NULL),
	 ('sunfire bangle','sunfire accessories','agility','agility',58000,NULL),
	 ('sunfire bracelet','sunfire accessories','agility','agility',58000,NULL),
	 ('sunfire gloves','sunfire accessories','power','power',580000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('sunfire headband','sunfire accessories','force','force',58000,NULL),
	 ('sunfire necklace','sunfire accessories','force','force',58000,NULL),
	 ('sunfire pendant','sunfire accessories','chakra','chakra',58000,NULL),
	 ('sunfire ring','sunfire accessories','power','power',580000,NULL),
	 ('uchiha amulet','uchiha accessories','chakra','chakra',47000,NULL),
	 ('uchiha bangle','uchiha accessories','agility','agility',49000,NULL),
	 ('uchiha bracelet','uchiha accessories','agility','agility',49000,NULL),
	 ('uchiha gloves','uchiha accessories','power','power',480000,NULL),
	 ('uchiha headband','uchiha accessories','force','force',47000,NULL),
	 ('uchiha necklace','uchiha accessories','force','force',47000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('uchiha pendant','uchiha accessories','chakra','chakra',47000,NULL),
	 ('uchiha ring','uchiha accessories','power','power',480000,NULL),
	 ('uzumaki amulet','uzumaki accessories','chakra','chakra',49000,NULL),
	 ('uzumaki bangle','uzumaki accessories','agility','agility',51000,NULL),
	 ('uzumaki bracelet','uzumaki accessories','agility','agility',51000,NULL),
	 ('uzumaki gloves','uzumaki accessories','power','power',500000,NULL),
	 ('uzumaki headband','uzumaki accessories','force','force',49000,NULL),
	 ('uzumaki necklace','uzumaki accessories','force','force',49000,NULL),
	 ('uzumaki pendant','uzumaki accessories','chakra','chakra',49000,NULL),
	 ('uzumaki ring','uzumaki accessories','power','power',500000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('vylon amulet','vylon accessories','chakra','chakra',59500,NULL),
	 ('vylon bangle','vylon accessories','agility','agility',59500,NULL),
	 ('vylon bracelet','vylon accessories','agility','agility',59500,NULL),
	 ('vylon gloves','vylon accessories','power','power',595000,NULL),
	 ('vylon headband','vylon accessories','force','force',59500,NULL),
	 ('vylon necklace','vylon accessories','force','force',59500,NULL),
	 ('vylon pendant','vylon accessories','chakra','chakra',59500,NULL),
	 ('vylon ring','vylon accessories','power','power',595000,NULL),
	 ('warlord amulet','warlord accessories','chakra','chakra',52000,NULL),
	 ('warlord bangle','warlord accessories','agility','agility',54000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('warlord bracelet','warlord accessories','agility','agility',54000,NULL),
	 ('warlord gloves','warlord accessories','power','power',530000,NULL),
	 ('warlord headband','warlord accessories','force','force',52000,NULL),
	 ('warlord necklace','warlord accessories','force','force',52000,NULL),
	 ('warlord pendant','warlord accessories','chakra','chakra',52000,NULL),
	 ('warlord R1 amulet','warlord R1 accessories','chakra','chakra',60000,NULL),
	 ('warlord R1 bangle','warlord R1 accessories','agility','agility',60000,NULL),
	 ('warlord R1 bracelet','warlord R1 accessories','agility','agility',60000,NULL),
	 ('warlord R1 gloves','warlord R1 accessories','power','power',600000,NULL),
	 ('warlord R1 headband','warlord R1 accessories','force','force',60000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('warlord R1 necklace','warlord R1 accessories','force','force',60000,NULL),
	 ('warlord R1 pendant','warlord R1 accessories','chakra','chakra',60000,NULL),
	 ('warlord R1 ring','warlord R1 accessories','power','power',600000,NULL),
	 ('warlord R2 amulet','warlord R2 accessories','chakra','chakra',65000,NULL),
	 ('warlord R2 bangle','warlord R2 accessories','agility','agility',65000,NULL),
	 ('warlord R2 bracelet','warlord R2 accessories','agility','agility',65000,NULL),
	 ('warlord R2 gloves','warlord R2 accessories','power','power',650000,NULL),
	 ('warlord R2 headband','warlord R2 accessories','force','force',65000,NULL),
	 ('warlord R2 necklace','warlord R2 accessories','force','force',65000,NULL),
	 ('warlord R2 pendant','warlord R2 accessories','chakra','chakra',65000,NULL);
INSERT INTO naruto.partes_accesorios (nombre,nombre_set,nombre_atributo,tipo,valor,image) VALUES
	 ('warlord R2 ring','warlord R2 accessories','power','power',650000,NULL),
	 ('warlord ring','warlord accessories','power','power',530000,NULL),
	 ('yaksa amulet','yaksa accessories','chakra','chakra',58500,NULL),
	 ('yaksa bangle','yaksa accessories','agility','agility',58500,NULL),
	 ('yaksa bracelet','yaksa accessories','agility','agility',58500,NULL),
	 ('yaksa gloves','yaksa accessories','power','power',585000,NULL),
	 ('yaksa headband','yaksa accessories','force','force',58500,NULL),
	 ('yaksa necklace','yaksa accessories','force','force',58500,NULL),
	 ('yaksa pendant','yaksa accessories','chakra','chakra',58500,NULL),
	 ('yaksa ring','yaksa accessories','power','power',585000,NULL);
