INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('amegakure armor','physical defense','amegakure set',59000,NULL),
	 ('amegakure belt','power','amegakure set',590000,NULL),
	 ('amegakure boots','speed','amegakure set',59000,NULL),
	 ('amegakure coat','strategy defense','amegakure set',59000,NULL),
	 ('amegakure headband','physical defense','amegakure set',59000,NULL),
	 ('amegakure kunai','physical attack','amegakure set',59000,NULL),
	 ('amegakure scroll','strategy attack','amegakure set',59000,NULL),
	 ('amegakure shuriken','physical attack','amegakure set',59000,NULL),
	 ('amenunohoko armor','physical defense','amenunohoko set',63000,NULL),
	 ('amenunohoko belt','power','amenunohoko set',630000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('amenunohoko boots','speed','amenunohoko set',63000,NULL),
	 ('amenunohoko coat','strategy defense','amenunohoko set',63000,NULL),
	 ('amenunohoko headband','physical defense','amenunohoko set',63000,NULL),
	 ('amenunohoko kunai','physical attack','amenunohoko set',63000,NULL),
	 ('amenunohoko scroll','strategy attack','amenunohoko set',63000,NULL),
	 ('amenunohoko shuriken','physical attack','amenunohoko set',63000,NULL),
	 ('arcane armor','physical defense','arcane set',70000,NULL),
	 ('arcane belt','power','arcane set',700000,NULL),
	 ('arcane boots','speed','arcane set',70000,NULL),
	 ('arcane coat','strategy defense','arcane set',70000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('arcane headband','physical defense','arcane set',70000,NULL),
	 ('arcane kunai','physical attack','arcane set',70000,NULL),
	 ('arcane scroll','strategy atatck','arcane set',70000,NULL),
	 ('arcane shuriken','physical attack','arcane set',70000,NULL),
	 ('ashura armor','physical defense','ashura set',44000,NULL),
	 ('ashura belt','power','ashura set',460000,NULL),
	 ('ashura boots','speed','ashura set',45000,NULL),
	 ('ashura coat','strategy defense','ashura set',44000,NULL),
	 ('ashura headband','physical defense','ashura set',44000,NULL),
	 ('ashura kunai','physical attack','ashura set',45000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('ashura scroll','strategy attack','ashura set',45000,NULL),
	 ('ashura shuriken','physical attack','ashura set',45000,NULL),
	 ('bloodfang armor','physical defense','bloodfang set',42000,NULL),
	 ('bloodfang belt','power','bloodfang set',440000,NULL),
	 ('bloodfang boots','speed','bloodfang set',44000,NULL),
	 ('bloodfang coat','strategy defense','bloodfang set',42000,NULL),
	 ('bloodfang headband','physical defense','bloodfang set',42000,NULL),
	 ('bloodfang kunai','physical attack','bloodfang set',44000,NULL),
	 ('bloodfang scroll','strategy attack','bloodfang set',44000,NULL),
	 ('bloodfang shuriken','physical attack','bloodfang set',44000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('curse seal armor','physical defense','curse seal set',54000,NULL),
	 ('curse seal belt','power','curse seal set',560000,NULL),
	 ('curse seal boots','speed','curse seal set',55000,NULL),
	 ('curse seal coat','strategy defense','curse seal set',54000,NULL),
	 ('curse seal headband','physical defense','curse seal set',54000,NULL),
	 ('curse seal kunai','physical attack','curse seal set',55000,NULL),
	 ('curse seal scroll','strategy attack','curse seal set',55000,NULL),
	 ('curse seal shuriken','physical attack','curse seal set',55000,NULL),
	 ('guard armor','physical defense','guard set',64000,NULL),
	 ('guard belt','power','guard set',640000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('guard boots','speed','guard set',64000,NULL),
	 ('guard coat','strategy defense','guard set',64000,NULL),
	 ('guard headband','physical defense','guard set',64000,NULL),
	 ('guard kunai','physical attack','guard set',64000,NULL),
	 ('guard scroll','strategy atatck','guard set',64000,NULL),
	 ('guard shuriken','physical attack','guard set',64000,NULL),
	 ('guren armor','physical defense','guren set',64000,NULL),
	 ('guren belt','power','guren set',640000,NULL),
	 ('guren boots','speed','guren set',64000,NULL),
	 ('guren coat','strategy defense','guren set',64000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('guren headband','physical defense','guren set',64000,NULL),
	 ('guren kunai','physical attack','guren set',64000,NULL),
	 ('guren scroll','strategy atatck','guren set',64000,NULL),
	 ('guren shuriken','physical attack','guren set',64000,NULL),
	 ('hyuga armor','physical defense','hyuga set',52000,NULL),
	 ('hyuga belt','power','hyuga set',540000,NULL),
	 ('hyuga boots','speed','hyuga set',53000,NULL),
	 ('hyuga coat','strategy defense','hyuga set',52000,NULL),
	 ('hyuga headband','physical defense','hyuga set',52000,NULL),
	 ('hyuga kunai','physical attack','hyuga set',53000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('hyuga scroll','strategy attack','hyuga set',53000,NULL),
	 ('hyuga shuriken','physical attack','hyuga set',53000,NULL),
	 ('indora armor','physical defense','indora set',42000,NULL),
	 ('indora belt','power','indora set',440000,NULL),
	 ('indora boots','speed','indora set',44000,NULL),
	 ('indora coat','strategy defense','indora set',42000,NULL),
	 ('indora headband','physical defense','indora set',42000,NULL),
	 ('indora kunai','physical attack','indora set',44000,NULL),
	 ('indora scroll','strategy attack','indora set',44000,NULL),
	 ('indora shuriken','physical attack','indora set',44000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('infernity armor','physical defense','infernity set',67500,NULL),
	 ('infernity belt','power','infernity set',675000,NULL),
	 ('infernity boots','speed','infernity set',67500,NULL),
	 ('infernity coat','strategy defense','infernity set',67500,NULL),
	 ('infernity headband','physical defense','infernity set',67500,NULL),
	 ('infernity kunai','physical attack','infernity set',67500,NULL),
	 ('infernity scroll','strategy atatck','infernity set',67500,NULL),
	 ('infernity shuriken','physical attack','infernity set',67500,NULL),
	 ('kirikakure armor','physical defense','kirikakure set',56000,NULL),
	 ('kirikakure belt','power','kirikakure set',580000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('kirikakure boots','speed','kirikakure set',57000,NULL),
	 ('kirikakure coat','strategy defense','kirikakure set',56000,NULL),
	 ('kirikakure headband','physical defense','kirikakure set',56000,NULL),
	 ('kirikakure kunai','physical attack','kirikakure set',57000,NULL),
	 ('kirikakure scroll','strategy attack','kirikakure set',57000,NULL),
	 ('kirikakure shuriken','physical attack','kirikakure set',57000,NULL),
	 ('kumogakure armor','physical defense','kumogakure set',57000,NULL),
	 ('kumogakure belt','power','kumogakure set',570000,NULL),
	 ('kumogakure boots','speed','kumogakure set',57000,NULL),
	 ('kumogakure coat','strategy defense','kumogakure set',57000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('kumogakure headband','physical defense','kumogakure set',57000,NULL),
	 ('kumogakure kunai','physical attack','kumogakure set',57000,NULL),
	 ('kumogakure scroll','strategy attack','kumogakure set',57000,NULL),
	 ('kumogakure shuriken','physical attack','kumogakure set',57000,NULL),
	 ('longen armor','physical defense','longen set',58000,NULL),
	 ('longen belt','power','longen set',580000,NULL),
	 ('longen boots','speed','longen set',58000,NULL),
	 ('longen coat','strategy defense','longen set',58000,NULL),
	 ('longen headband','physical defense','longen set',58000,NULL),
	 ('longen kunai','physical attack','longen set',58000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('longen scroll','strategy attack','longen set',58000,NULL),
	 ('longen shuriken','physical attack','longen set',58000,NULL),
	 ('moonlit armor','physical defense','moonlit set',68000,NULL),
	 ('moonlit belt','power','moonlit set',680000,NULL),
	 ('moonlit boots','speed','moonlit set',68000,NULL),
	 ('moonlit coat','strategy defense','moonlit set',68000,NULL),
	 ('moonlit headband','physical defense','moonlit set',68000,NULL),
	 ('moonlit kunai','physical attack','moonlit set',68000,NULL),
	 ('moonlit scroll','strategy atatck','moonlit set',68000,NULL),
	 ('moonlit shuriken','physical attack','moonlit set',68000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('pain armor','physical defense','pain set',54000,NULL),
	 ('pain belt','power','pain set',560000,NULL),
	 ('pain boots','speed','pain set',55000,NULL),
	 ('pain coat','strategy defense','pain set',54000,NULL),
	 ('pain headband','physical defense','pain set',54000,NULL),
	 ('pain kunai','physical attack','pain set',55000,NULL),
	 ('pain scroll','strategy attack','pain set',55000,NULL),
	 ('pain shuriken','physical attack','pain set',55000,NULL),
	 ('saint armor','physical defense','saint set',48000,NULL),
	 ('saint belt','power','saint set',500000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('saint boots','speed','saint set',49000,NULL),
	 ('saint coat','strategy defense','saint set',48000,NULL),
	 ('saint headband','physical defense','saint set',48000,NULL),
	 ('saint kunai','physical attack','saint set',49000,NULL),
	 ('saint scroll','strategy attack','saint set',49000,NULL),
	 ('saint shuriken','physical attack','saint set',49000,NULL),
	 ('sakura armor','physical defense','sakura set',60000,NULL),
	 ('sakura belt','power','sakura set',600000,NULL),
	 ('sakura boots','speed','sakura set',60000,NULL),
	 ('sakura coat','strategy defense','sakura set',60000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('sakura headband','physical defense','sakura set',60000,NULL),
	 ('sakura kunai','physical attack','sakura set',60000,NULL),
	 ('sakura scroll','strategy attack','sakura set',60000,NULL),
	 ('sakura shuriken','physical attack','sakura set',60000,NULL),
	 ('sarutobi armor','physical defense','sarutobi set',54000,NULL),
	 ('sarutobi belt','power','sarutobi set',560000,NULL),
	 ('sarutobi boots','speed','sarutobi set',55000,NULL),
	 ('sarutobi coat','strategy defense','sarutobi set',54000,NULL),
	 ('sarutobi headband','physical defense','sarutobi set',54000,NULL),
	 ('sarutobi kunai','physical attack','sarutobi set',55000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('sarutobi scroll','strategy attack','sarutobi set',55000,NULL),
	 ('sarutobi shuriken','physical attack','sarutobi set',55000,NULL),
	 ('senju armor','physical defense','senju set',46000,NULL),
	 ('senju belt','power','senju set',480000,NULL),
	 ('senju boots','speed','senju set',47000,NULL),
	 ('senju coat','strategy defense','senju set',46000,NULL),
	 ('senju headband','physical defense','senju set',46000,NULL),
	 ('senju kunai','physical attack','senju set',47000,NULL),
	 ('senju scroll','strategy attack','senju set',47000,NULL),
	 ('senju shuriken','physical attack','senju set',47000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('sunagakure armor','physical defense','sunagakure set',61000,NULL),
	 ('sunagakure belt','power','sunagakure set',610000,NULL),
	 ('sunagakure boots','speed','sunagakure set',61000,NULL),
	 ('sunagakure coat','strategy defense','sunagakure set',61000,NULL),
	 ('sunagakure headband','physical defense','sunagakure set',61000,NULL),
	 ('sunagakure kunai','physical attack','sunagakure set',61000,NULL),
	 ('sunagakure scroll','strategy attack','sunagakure set',61000,NULL),
	 ('sunagakure shuriken','physical attack','sunagakure set',61000,NULL),
	 ('sunfire armor','physical defense','sunfire set',67500,NULL),
	 ('sunfire belt','power','sunfire set',675000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('sunfire boots','speed','sunfire set',67500,NULL),
	 ('sunfire coat','strategy defense','sunfire set',67500,NULL),
	 ('sunfire headband','physical defense','sunfire set',67500,NULL),
	 ('sunfire kunai','physical attack','sunfire set',67500,NULL),
	 ('sunfire scroll','strategy atatck','sunfire set',67500,NULL),
	 ('sunfire shuriken','physical attack','sunfire set',67500,NULL),
	 ('uchiha armor','physical defense','uchiha set',50000,NULL),
	 ('uchiha belt','power','uchiha set',520000,NULL),
	 ('uchiha boots','speed','uchiha set',51000,NULL),
	 ('uchiha coat','strategy defense','uchiha set',50000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('uchiha headband','physical defense','uchiha set',50000,NULL),
	 ('uchiha kunai','physical attack','uchiha set',51000,NULL),
	 ('uchiha scroll','strategy attack','uchiha set',51000,NULL),
	 ('uchiha shuriken','physical attack','uchiha set',51000,NULL),
	 ('uzumaki armor','physical defense','uzumaki set',52000,NULL),
	 ('uzumaki belt','power','uzumaki set',540000,NULL),
	 ('uzumaki boots','speed','uzumaki set',53000,NULL),
	 ('uzumaki coat','strategy defense','uzumaki set',52000,NULL),
	 ('uzumaki headband','physical defense','uzumaki set',52000,NULL),
	 ('uzumaki kunai','physical attack','uzumaki set',53000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('uzumaki scroll','strategy attack','uzumaki set',53000,NULL),
	 ('uzumaki shuriken','physical attack','uzumaki set',53000,NULL),
	 ('vylon armor','physical defense','vylon set',68500,NULL),
	 ('vylon belt','power','vylon set',685000,NULL),
	 ('vylon boots','speed','vylon set',68500,NULL),
	 ('vylon coat','strategy defense','vylon set',68500,NULL),
	 ('vylon headband','physical defense','vylon set',68500,NULL),
	 ('vylon kunai','physical attack','vylon set',68500,NULL),
	 ('vylon scroll','strategy atatck','vylon set',68500,NULL),
	 ('vylon shuriken','physical attack','vylon set',68500,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('warlord R4 armor','physical defense','warlord R4 set',66000,NULL),
	 ('warlord R4 belt','power','warlord R4 set',660000,NULL),
	 ('warlord R4 boots','speed','warlord R4 set',66000,NULL),
	 ('warlord R4 coat','strategy defense','warlord R4 set',66000,NULL),
	 ('warlord R4 headband','physical defense','warlord R4 set',66000,NULL),
	 ('warlord R4 kunai','physical attack','warlord R4 set',66000,NULL),
	 ('warlord R4 scroll','strategy atatck','warlord R4 set',66000,NULL),
	 ('warlord R4 shuriken','physical attack','warlord R4 set',66000,NULL),
	 ('yaksa armor','physical defense','yaksa set',67500,NULL),
	 ('yaksa belt','power','yaksa set',675000,NULL);
INSERT INTO naruto.partes (nombre,nombre_atributo,nombre_equipo,valor,image) VALUES
	 ('yaksa boots','speed','yaksa set',67500,NULL),
	 ('yaksa coat','strategy defense','yaksa set',67500,NULL),
	 ('yaksa headband','physical defense','yaksa set',67500,NULL),
	 ('yaksa kunai','physical attack','yaksa set',67500,NULL),
	 ('yaksa scroll','strategy atatck','yaksa set',67500,NULL),
	 ('yaksa shuriken','physical attack','yaksa set',67500,NULL);
